version: '3'
  
services:

    backend:
        image: youisland_nodejs:${TAG}
        build:
            ./youisland_nodejs
        # container_name: backend
        volumes: 
            - .google_cloud.json:/app/.google_cloud.json

        env_file:
            - .env
        ports:
            - 3000:3000

    frontend:
        image: youisland_php:${TAG}
        build:
            ./youisland_php
        ports:
            - 5001:80
        depends_on:
            - backend
        